@startuml
left to right direction

actor комендант
actor студент

usecase "Обработать заявки студентов" as U1
usecase "Выселить" as U2
usecase "Заселить" as U3
usecase "Переселить" as U4

usecase "Управление студентами" as U5
usecase "Посмотреть список студентов в общяге" as U6
usecase "Выселение студента" as U8

usecase "Посмотреть комнаты" as U9
usecase "Просмотр свободных комнат" as U10
usecase "Промотр заполненных комнат" as U11




usecase "Подать заявку" as U12
usecase "Выселиться" as U13
usecase "Заселиться" as U14
usecase "Переселиться" as U15
usecase "Посмотреть заявки" as U16

комендант -- U1
комендант -- U5
комендант -- U9

студент -- U12
студент -- U16

U1 -- U2
U1 -- U3
U1 -- U4

U5 -- U6
U5 -- U8

U9 -- U10
U9 -- U11

U12 -- U13
U12 -- U14
U12 -- U15


@enduml